CREATE TABLE STUDENTS(
    ROLL VARCHAR2(10) PRIMARY KEY,
    FIRST_NAME VARCHAR2(20) NOT NULL,
    LAST_NAME VARCHAR2(20) NOT NULL,
    DEPT VARCHAR2(3) NOT NULL,
    MOBILE VARCHAR2(10) NOT NULL,
    SEX VARCHAR2(1) NOT NULL CHECK(SEX='M' OR SEX = 'F'),
    EMAIL VARCHAR2(10) NOT NULL,
    MONTH NUMBER(2) NOT NULL CHECK(MONTH<=12 AND MONTH >=1),
    DAY NUMBER(2) NOT NULL CHECK(DAY <=31 AND DAY>=1),
    YEAR NUMBER(4) NOT NULL,
    PIC BLOB
);

INSERT INTO STUDENTS VALUES('roll' , 'first_name' , 'last_name' , 'dept' , 'mobile' , 'sex' , 'email' , month , day , year , PIC)
